---
# - name: Update apt cache
#   ansible.builtin.apt:
#     update_cache: yes

# - name: Add MongoDB public GPG key for 5.0
#   ansible.builtin.apt_key:
#     url: https://pgp.mongodb.com/server-5.0.asc
#     state: present

# - name: Create MongoDB list file for 5.0
#   ansible.builtin.apt_repository:
#     repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse"
#     state: present

# - name: Download libssl1.1 for Ubuntu 20.04
#   ansible.builtin.get_url:
#     url: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
#     dest: /tmp/libssl1.1.deb

# - name: Install libssl1.1 package
#   ansible.builtin.apt:
#     deb: /tmp/libssl1.1.deb

# - name: Install pip for Python 3
#   ansible.builtin.apt:
#     name: python3-pip
#     state: present

# - name: Install pymongo
#   ansible.builtin.pip:
#     name: pymongo
#     state: present

# - name: Install MongoDB
#   ansible.builtin.apt:
#     name: mongodb-org
#     state: present

# - name: Start MongoDB
#   ansible.builtin.service:
#     name: mongod
#     state: started
#     enabled: yes

- name: Download MongoDB GPG key
  ansible.builtin.get_url:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    dest: /tmp/mongodb-server-6.0.asc

- name: Add MongoDB GPG key to keyring
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/mongodb-archive-keyring.gpg /tmp/mongodb-server-6.0.asc
  become: yes

- name: Remove temporary GPG key file
  ansible.builtin.file:
    path: /tmp/mongodb-server-6.0.asc
    state: absent

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install MongoDB
  ansible.builtin.apt:
    name: mongodb-org
    state: present

- name: Start and enable MongoDB service
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: yes